version: '3.8'

services:
  portfolio:
    container_name: portfolio_nextjs
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000
    networks:
      - proxy
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hostelinev2.rule=Host(`portfolio.gonzalezjoan.com`)"
      - "traefik.http.services.hostelinev2.loadbalancer.server.port=3000"
      - "traefik.http.routers.hostelinev2.entrypoints=websecure"
      - traefik.http.routers.hostelinev2.tls=true
      - traefik.http.routers.hostelinev2.tls.certresolver=letsencrypt
      - "traefik.docker.network=proxy"
    volumes:
      - ./public:/app/public
    restart: always

networks:
  proxy:
    external: true
  internal:
